// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251124155836_AddProductsModel")]
    partial class AddProductsModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Model.MUnitModel", b =>
                {
                    b.Property<int>("MUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MUnitId"));

                    b.Property<string>("MUnitCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MUnitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MUnitId");

                    b.ToTable("Munit");
                });

            modelBuilder.Entity("API.Model.ProductsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ProductCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductQty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("API.Model.PurchaseRequestmodel", b =>
                {
                    b.Property<int>("PRID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PRID"));

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("MUnitId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PRDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PRNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRQuantity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PRID");

                    b.HasIndex("Id");

                    b.HasIndex("MUnitId");

                    b.ToTable("PurchaseRequestmodels");
                });

            modelBuilder.Entity("API.Model.PurchaseRequestmodel", b =>
                {
                    b.HasOne("API.Model.ProductsModel", "Product")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Model.MUnitModel", "MUnit")
                        .WithMany()
                        .HasForeignKey("MUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MUnit");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
